server:
  port: 8999
logging:
  file: ./rest-handler.log
info:
  component: Rest-Handler
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
c2s.dss.context-path: "dss"
---
spring:
  profiles: local
c2s.dss.context-path: "http://52.201.231.59:8450"